/* =================================================================
   scripts/build-agent.js — compile backend/agent-src/ into
   backend/lib/codeagent/
   -----------------------------------------------------------------
   The output lands in a directory full of hand-written JavaScript,
   which is the whole risk of this arrangement: name a source
   agent-src/model-loop.ts and tsc would quietly overwrite 3581 lines
   of someone else's work with a compiled stub, and the first sign of
   it would be a test suite that got shorter.

   So the collision check runs BEFORE tsc, not after. It refuses the
   build rather than reporting the damage.

   Run: npm run build:agent
   ================================================================= */
"use strict";

const fs = require("fs");
const path = require("path");
const { spawnSync } = require("child_process");

const BACKEND = path.join(__dirname, "..");
const SRC = path.join(BACKEND, "agent-src");
const OUT = path.join(BACKEND, "lib", "codeagent");

const BANNER = "/* GENERATED FROM backend/agent-src/";

/** Every .ts under agent-src/, as the .js path tsc would emit for it. */
function emittedPaths(dir, rel) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const abs = path.join(dir, entry.name);
    const here = rel ? rel + "/" + entry.name : entry.name;
    if (entry.isDirectory()) { out.push(...emittedPaths(abs, here)); continue; }
    if (!entry.name.endsWith(".ts") || entry.name.endsWith(".d.ts")) continue;
    out.push(here.replace(/\.ts$/, ".js"));
  }
  return out;
}

/** A file in the output tree that this build did not produce. */
function isHandWritten(relJs) {
  const abs = path.join(OUT, relJs);
  if (!fs.existsSync(abs)) return false;
  // Everything this script emits carries the banner tsc cannot fake.
  return !fs.readFileSync(abs, "utf8").startsWith(BANNER);
}

const emitted = emittedPaths(SRC, "");
const collisions = emitted.filter(isHandWritten);

if (collisions.length) {
  console.error(
    "\n✗ build:agent refused: these would overwrite hand-written files in lib/codeagent/\n" +
    collisions.map((c) => "    " + c).join("\n") +
    "\n\n  Rename the source in agent-src/, or port the hand-written file deliberately.\n"
  );
  process.exit(1);
}

/* Resolved through node rather than shelled out to `npx`. Under Git Bash
   on Windows, spawnSync("npx.cmd") fails to launch and returns status
   null with the reason on `.error` — so the build exited 1 having
   printed nothing at all, which is a worse failure than not building. */
const tscBin = require.resolve("typescript/bin/tsc");
const tsc = spawnSync(
  process.execPath,
  [tscBin, "-p", path.join(SRC, "tsconfig.json")],
  { cwd: BACKEND, stdio: "inherit" }
);
if (tsc.error) {
  console.error("\n✗ build:agent could not start tsc: " + tsc.error.message + "\n");
  process.exit(1);
}
if (tsc.status !== 0) process.exit(tsc.status === null ? 1 : tsc.status);

/* Stamp each emitted file so the next run can tell its own output from
   a file a person wrote, and so nobody edits the wrong copy. */
let stamped = 0;
for (const rel of emitted) {
  const abs = path.join(OUT, rel);
  if (!fs.existsSync(abs)) continue;
  const body = fs.readFileSync(abs, "utf8");
  if (body.startsWith(BANNER)) { stamped++; continue; }
  const src = "agent-src/" + rel.replace(/\.js$/, ".ts");
  fs.writeFileSync(
    abs,
    BANNER + "\n   Do not edit this file. Edit " + src + " and run `npm run build:agent`.\n" +
    "   Listed in docs/REPO-MAP.md beside the other generated files. */\n" + body
  );
  stamped++;
}

console.log("✓ build:agent — " + stamped + " file" + (stamped === 1 ? "" : "s") + " emitted into lib/codeagent/");
