/* GENERATED FROM backend/agent-src/
   Do not edit this file. Edit agent-src/lib/codeagent/context/auto-compact.ts and run `npm run build:agent`.
   Listed in docs/REPO-MAP.md beside the other generated files. */
"use strict";
/* =================================================================
   context/auto-compact.ts — replace the middle, keep what it meant
   -----------------------------------------------------------------
   When shrinking tool output is no longer enough, the conversation
   itself has to go. fitConversation's answer is to drop whole repair
   groups oldest-first, which is correct as a last resort and lossy in
   a particular way: what it drops is the early turns, and the early
   turns are where the user said what they wanted.

   So this runs first, and turns the middle of the conversation into
   one message instead of removing it. The head (system prompt, the
   codebase, the task) and the most recent turns are kept verbatim.

   WHAT THE SUMMARY HAS TO CARRY is the whole design. A summary that
   reads well and loses one constraint is worse than no summary,
   because the model now has a confident account of the task with the
   constraint missing from it. The sections below are the things a
   Souqi run cannot afford to forget, and they are not a general list:

     - the request, in the user's own words. Paraphrasing it is how
       "a barber shop in Casablanca" becomes "a salon website".
     - constraints the user stated. These are the ones that get lost.
     - plan / approval / question state, because a run that was
       holding for an answer must still be holding after compaction.
     - files, with content hashes, so the next turn can tell whether
       what it remembers is still what is on disk.
     - what was verified, and by what. A browser check is a client
       claim; a summary that records it as "tests passed" launders it.
     - what is still outstanding.

   The raw transcript is not destroyed. agent_steps has every turn's
   tool calls and results, written before this runs.
   ================================================================= */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.SUMMARY_MARKER = void 0;
exports.factsBlock = factsBlock;
exports.autoCompact = autoCompact;
exports.isSummary = isSummary;
const client = __importStar(require("../../ai/client"));
const redact_1 = require("./redact");
exports.SUMMARY_MARKER = "[context summary]";
/* ── the deterministic summary ──────────────────────────────────── */
/**
 * Built from FACTS the runner already tracked, not from reading the
 * transcript back.
 *
 * This is the fallback when there is no provider call to spare, and it
 * is also the floor under the model-written one: everything here is
 * something the orchestrator knows for certain, so none of it can be
 * hallucinated away. The model's version is appended to it rather than
 * replacing it.
 */
function factsBlock(facts) {
    const f = (0, redact_1.redactDeep)(facts || {});
    const out = [exports.SUMMARY_MARKER];
    if (f.prompt) {
        out.push("", "The user asked, in their own words:", '  "' + String(f.prompt).slice(0, 1200) + '"');
    }
    const state = [];
    if (f.mode)
        state.push("mode: " + f.mode);
    if (f.approvalReason)
        state.push("approval: " + f.approvalReason);
    if (f.pendingQuestion) {
        state.push('AWAITING AN ANSWER to question ' + f.pendingQuestion.id + ': "' + f.pendingQuestion.text + '"');
    }
    if (state.length)
        out.push("", "Run state:", ...state.map((s) => "  - " + s));
    const written = f.filesWritten || [];
    const edited = f.filesEdited || [];
    if (written.length || edited.length) {
        out.push("", "Files changed so far:");
        for (const p of written)
            out.push("  - wrote " + p + hashSuffix(f.fileHashes, p));
        for (const p of edited)
            out.push("  - edited " + p + hashSuffix(f.fileHashes, p));
        out.push("  (the hashes are what these were when last seen — re-read a file" +
            " before editing it if you need to be sure it has not moved on.)");
    }
    if (f.verification) {
        const v = f.verification;
        out.push("", "Verification:", "  - " + v.kind + ": " + (v.passed ? "passed" : "failed") +
            (v.attested ? " (attested)" : " (UNATTESTED — a client reported this; it is not proof)"));
    }
    const errs = (f.errors || []).slice(-6);
    if (errs.length) {
        out.push("", "Errors and refusals seen (most recent last):", ...errs.map((e) => "  - " + String(e).slice(0, 220)));
    }
    return out.join("\n");
}
function hashSuffix(hashes, path) {
    const h = hashes && hashes[path];
    return h ? "  [" + String(h).slice(0, 12) + "]" : "";
}
/* ── the model-written half ─────────────────────────────────────── */
const SUMMARY_PROMPT = "You are compacting the middle of an engineering transcript so the work can continue " +
    "without it. Write a factual account, in plain prose, of:\n" +
    "  - what has been attempted and what came of it;\n" +
    "  - any constraint or preference the user stated, quoted exactly;\n" +
    "  - decisions taken and why, including ones later reversed;\n" +
    "  - what remains to be done.\n\n" +
    "Rules. Do not restate the user's original request — it is preserved verbatim elsewhere. " +
    "Do not describe anything as verified, passing or complete unless the transcript shows " +
    "the result of an actual check. Do not invent file names. If something is unresolved, " +
    "say that it is unresolved. No preamble, no markdown headings, under 400 words.";
async function modelSummary(messages, opts) {
    const transcript = messages
        .map((m) => String(m.role) + ": " + (0, redact_1.redact)(typeof m.content === "string" ? m.content : "").text.slice(0, 2000))
        .join("\n")
        .slice(-24000);
    const res = await client.chat({
        route: opts.route || "prose",
        model: opts.model,
        messages: [
            { role: "system", content: SUMMARY_PROMPT },
            { role: "user", content: transcript }
        ],
        maxTokens: 700,
        temperature: 0.2,
        timeoutMs: 30000
    });
    if (!res || !res.ok)
        return "";
    const text = res.message && typeof res.message.content === "string" ? res.message.content.trim() : "";
    return (0, redact_1.redact)(text).text;
}
/* ── the operation ──────────────────────────────────────────────── */
/**
 * Replace the middle of `messages` with one summary message.
 *
 * Returns the input untouched when there is nothing in the middle
 * worth replacing — compaction that saves two messages costs a
 * provider call to make the request marginally smaller and the
 * transcript meaningfully worse.
 */
async function autoCompact(messages, opts = {}) {
    const headLen = Math.max(1, Number(opts.headLen) || 1);
    const keepRecent = opts.keepRecent === undefined ? 8 : Number(opts.keepRecent);
    const facts = opts.facts || {};
    const middleStart = headLen;
    const middleEnd = Math.max(headLen, messages.length - keepRecent);
    const middle = messages.slice(middleStart, middleEnd);
    if (middle.length < 4) {
        return { messages, replaced: 0, summary: "", modelWritten: false };
    }
    const floor = factsBlock(facts);
    let prose = "";
    let modelWritten = false;
    try {
        prose = opts.summarise ? await opts.summarise(middle, facts) : await modelSummary(middle, opts);
        modelWritten = !!prose;
    }
    catch {
        /* A compaction that cannot reach the provider still has to produce
           something, because the alternative is dropping the middle with
           nothing in its place. The facts block is that something. */
        prose = "";
    }
    const summary = prose ? floor + "\n\nWhat happened in the part of this conversation that was compacted:\n" + prose : floor;
    /* One user message, not a system one. A second system message is a
       second set of instructions as far as the model is concerned, and
       this is a report about the conversation rather than a rule. */
    const summaryMessage = { role: "user", content: summary };
    return {
        messages: messages.slice(0, middleStart).concat([summaryMessage], messages.slice(middleEnd)),
        replaced: middle.length,
        summary,
        modelWritten
    };
}
/** Is this message one of ours? Used to avoid compacting a summary
    into a summary of a summary. */
function isSummary(message) {
    return !!message && typeof message.content === "string" && message.content.startsWith(exports.SUMMARY_MARKER);
}
