/* GENERATED FROM backend/agent-src/
   Do not edit this file. Edit agent-src/lib/codeagent/context/context-manager.ts and run `npm run build:agent`.
   Listed in docs/REPO-MAP.md beside the other generated files. */
"use strict";
/* =================================================================
   context/context-manager.ts — assemble the request, every call
   -----------------------------------------------------------------
   The one entry point the runner uses. Everything else in this
   directory is a step it can take; this decides which steps this
   particular call needs and in what order.

   The order is not arbitrary. Each step is more expensive and more
   lossy than the one before it, so each runs only when the cheaper
   ones have not been enough:

     1. measure          — free
     2. micro-compact    — free, and the raw record survives in
                           agent_steps
     3. auto-compact     — one provider call, and detail is lost
     4. fitConversation  — free, and whole turns are lost

   Step 4 already existed and is the reason for the other three. Its
   only move is to drop, so anything that reduces the request before
   it runs is a turn it does not have to throw away.

   REASSEMBLED EVERY CALL, not accumulated. The alternative — mutate
   one array and keep appending — is how a run ends up with a
   conversation nobody can account for, where the thing that trimmed
   it three turns ago has already removed the message that explains
   why the current one looks wrong. Given the same inputs this returns
   the same request.
   ================================================================= */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.auto = exports.micro = exports.budget = void 0;
exports.prepare = prepare;
const model_loop_1 = require("../model-loop");
const budget = __importStar(require("./token-budget"));
exports.budget = budget;
const micro = __importStar(require("./micro-compact"));
exports.micro = micro;
const auto = __importStar(require("./auto-compact"));
exports.auto = auto;
/**
 * Turn an accumulated conversation into a request that fits.
 *
 * Never throws: a context engine that fails is a run that fails, and
 * the fallback — hand back the messages it was given and let
 * fitConversation deal with them — is what happened before any of this
 * existed. Each step is attempted, and a step that cannot run is
 * recorded and skipped.
 */
async function prepare(input) {
    const tools = input.tools;
    const b = budget.budgetFor({
        route: input.route, model: input.model, maxTokens: input.maxTokens, tools
    });
    let messages = input.messages || [];
    const before = budget.measure(messages, b, tools);
    const actions = [];
    // 2 — cheap, and the cleared text stays readable in agent_steps.
    if (before.needsMicroCompact) {
        const r = micro.microCompact(messages, { runId: input.runId });
        if (r.compacted) {
            messages = r.messages;
            actions.push({
                step: "micro-compact", removed: r.charsFreed,
                detail: r.compacted + " old tool result" + (r.compacted === 1 ? "" : "s") +
                    " cleared, " + r.charsFreed + " chars freed"
            });
        }
    }
    // 3 — only if shrinking the bulk was not enough.
    let mid = budget.measure(messages, b, tools);
    if (mid.needsAutoCompact) {
        try {
            const r = await auto.autoCompact(messages, {
                headLen: input.headLen,
                keepRecent: input.keepRecent,
                facts: input.facts || {},
                summarise: input.summarise,
                route: input.route,
                model: input.model
            });
            if (r.replaced) {
                messages = r.messages;
                actions.push({
                    step: "auto-compact", removed: r.replaced,
                    detail: r.replaced + " messages replaced by a " +
                        (r.modelWritten ? "written" : "facts-only") + " summary"
                });
            }
        }
        catch (e) {
            /* Compaction failing is not a reason to fail the turn — step 4
               can still make this fit, it will just cost whole rounds. */
            actions.push({ step: "auto-compact", removed: 0, detail: "skipped: " + e.message });
        }
        mid = budget.measure(messages, b, tools);
    }
    // 4 — the existing trimmer, and now the last resort rather than the first.
    if (mid.ratio >= 1) {
        const fit = (0, model_loop_1.fitConversation)(messages, {
            windowTokens: b.windowTokens,
            maxTokens: b.replyTokens,
            tools,
            headLen: input.headLen
        });
        if (fit.dropped) {
            messages = fit.messages;
            actions.push({
                step: "fit", removed: fit.dropped,
                detail: fit.dropped + " message group" + (fit.dropped === 1 ? "" : "s") + " dropped to fit the window"
            });
        }
    }
    return { messages, budget: b, before, after: budget.measure(messages, b, tools), actions };
}
