/* GENERATED FROM backend/agent-src/
   Do not edit this file. Edit agent-src/lib/codeagent/context/redact.ts and run `npm run build:agent`.
   Listed in docs/REPO-MAP.md beside the other generated files. */
"use strict";
/* =================================================================
   context/redact.ts — what must not survive into a summary
   -----------------------------------------------------------------
   Compaction and project memory both take text that was once
   transient and make it durable: a summary is written back into
   every later turn, and a remembered rule can outlive the project
   that produced it. So a secret that appears once in a tool result
   is a secret in a database afterwards.

   The generated app is where this actually bites. A model writing a
   payment integration puts a key in the file it is writing, the file
   comes back through a tool result, and the tool result is what gets
   summarised. Nothing here can stop the key being written — that is
   the model's business and the scaffold's — but it can stop the key
   being the one part of the turn that gets kept forever.

   Deliberately conservative about what counts. A false positive
   costs a summary the word "sk-something"; a false negative costs a
   customer their Stripe key. The patterns are anchored to shapes
   that are not ordinary prose.
   ================================================================= */
Object.defineProperty(exports, "__esModule", { value: true });
exports.redact = redact;
exports.hasSecret = hasSecret;
exports.redactDeep = redactDeep;
/* Each entry is a shape, not a vendor list — a vendor list goes stale
   the moment somebody adds a provider. `label` is what replaces the
   match, so a reader can see WHAT was removed without seeing it. */
const PATTERNS = [
    /* Anything that announces itself: sk-..., pk_live_..., ghp_..., xoxb-...
       The tail allows internal dashes and underscores, and it has to: this
       required 16 straight alphanumerics after the prefix, so it matched
       sk_live_abc... and missed sk-ant-api03-... and sk-proj-... entirely —
       it gave up three characters in, at the dash in "ant-api03". Both of
       the two most common key formats in a repo this agent reads walked
       through it. Found when a streamed reply carried one. */
    { re: /\b(?:sk|pk|rk|ak)[-_](?:live|test|prod)?[-_]?[A-Za-z0-9][A-Za-z0-9_-]{14,}[A-Za-z0-9]\b/g,
        label: "[redacted: api key]" },
    { re: /\bgh[pousr]_[A-Za-z0-9]{20,}\b/g, label: "[redacted: github token]" },
    { re: /\bxox[baprs]-[A-Za-z0-9-]{10,}\b/g, label: "[redacted: slack token]" },
    { re: /\bAKIA[0-9A-Z]{16}\b/g, label: "[redacted: aws key id]" },
    // A JWT is three base64url segments joined by dots, and nothing else is.
    { re: /\beyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\b/g, label: "[redacted: jwt]" },
    // Connection strings carry the password in the authority.
    { re: /\b(?:mongodb(?:\+srv)?|postgres(?:ql)?|mysql|redis|amqp):\/\/[^\s"'<>]*:[^\s"'@<>]+@[^\s"'<>]+/gi,
        label: "[redacted: connection string]" },
    // `SOMETHING_SECRET = "..."` / `apiKey: '...'` — the assignment is the tell.
    { re: /\b([A-Za-z_][A-Za-z0-9_]*(?:SECRET|PASSWORD|PASSWD|TOKEN|APIKEY|API_KEY|PRIVATE_KEY|ACCESS_KEY)[A-Za-z0-9_]*)\s*[:=]\s*["'`][^"'`\n]{6,}["'`]/gi,
        label: "$1 = [redacted]" },
    // -----BEGIN ... PRIVATE KEY----- ... -----END ... -----
    { re: /-----BEGIN [A-Z ]*PRIVATE KEY-----[\s\S]*?-----END [A-Z ]*PRIVATE KEY-----/g,
        label: "[redacted: private key block]" }
];
/**
 * Returns the text with anything secret-shaped replaced, and a count.
 *
 * The count is the useful half: a caller that redacted something can
 * say so in the log instead of logging the thing it redacted.
 */
function redact(input) {
    let text = typeof input === "string" ? input : String(input ?? "");
    let redacted = 0;
    for (const { re, label } of PATTERNS) {
        text = text.replace(re, (...args) => {
            redacted++;
            // $1 in a label means "keep the name, drop the value".
            return label.includes("$1") ? label.replace("$1", String(args[1] ?? "")) : label;
        });
    }
    return { text, redacted };
}
/** True when the input contains something worth not keeping. */
function hasSecret(input) {
    return redact(input).redacted > 0;
}
/** Redact every string in a structure, leaving its shape alone. */
function redactDeep(value) {
    if (typeof value === "string")
        return redact(value).text;
    if (Array.isArray(value))
        return value.map(redactDeep);
    if (value && typeof value === "object") {
        const out = {};
        for (const [k, v] of Object.entries(value))
            out[k] = redactDeep(v);
        return out;
    }
    return value;
}
