/* GENERATED FROM backend/agent-src/
   Do not edit this file. Edit agent-src/lib/codeagent/context/token-budget.ts and run `npm run build:agent`.
   Listed in docs/REPO-MAP.md beside the other generated files. */
"use strict";
/* =================================================================
   context/token-budget.ts — how much room is left, measured
   -----------------------------------------------------------------
   The existing budget work is good and is not replaced here.
   codeBudgetChars computes the codebase allowance from the model's
   real window, and fitConversation keeps a conversation inside it.
   What neither answers is "how close are we?", because both are
   called at the moment something has to be cut.

   That matters because fitConversation's only move is to DROP —
   whole repair groups, oldest first. By the time it runs, the choice
   is already between losing a round entirely and failing the call.
   Compaction needs to act earlier than that, and to act earlier it
   needs pressure as a number rather than as an exception.

   Thresholds are fractions of the usable window, not message counts.
   A message count is a proxy for size that is wrong in both
   directions: forty short turns fit comfortably, and three turns
   carrying a 24,000-character read_file do not.
   ================================================================= */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.AUTO_COMPACT_AT = exports.MICRO_COMPACT_AT = exports.SAFETY_MARGIN_TOKENS = void 0;
exports.budgetFor = budgetFor;
exports.measure = measure;
exports.canSpend = canSpend;
const client = __importStar(require("../../ai/client"));
/** Reserved above the reply so a slightly-wrong estimate is not fatal.
    The same 512 fitConversation uses; kept in step deliberately. */
exports.SAFETY_MARGIN_TOKENS = 512;
/* Measured against the USABLE window — what is left after the reply and
   the margin are set aside — because that is the number the request is
   actually competing for.

   0.60 / 0.85 rather than something tighter: micro-compaction is cheap
   and lossless-ish (the raw record stays in agent_steps), so it can run
   early and often. Full compaction costs a provider call and loses
   detail, so it waits until dropping is otherwise imminent. */
exports.MICRO_COMPACT_AT = 0.60;
exports.AUTO_COMPACT_AT = 0.85;
function budgetFor(input) {
    const route = input.route || "json";
    const windowTokens = client.windowFor(route, input.model);
    const replyTokens = Math.max(0, Number(input.maxTokens) || 0);
    return {
        windowTokens,
        replyTokens,
        usableTokens: Math.max(0, windowTokens - replyTokens - exports.SAFETY_MARGIN_TOKENS),
        route,
        model: input.model
    };
}
/**
 * What the conversation costs right now, against what it may spend.
 *
 * `tools` counts. The schemas are sent on every single call, and
 * leaving them out of the estimate is how a budget that looked fine
 * produces a request that does not fit.
 */
function measure(messages, budget, tools) {
    const usedTokens = client.estimateTokens(messages, tools);
    const usable = budget.usableTokens || 1;
    const ratio = usedTokens / usable;
    return {
        usedTokens,
        usableTokens: budget.usableTokens,
        ratio,
        needsMicroCompact: ratio >= exports.MICRO_COMPACT_AT,
        needsAutoCompact: ratio >= exports.AUTO_COMPACT_AT,
        overflowing: ratio >= 1
    };
}
/**
 * Asked BEFORE a call, not after.
 *
 * Checking afterwards records an overspend rather than preventing one,
 * and the run whose budget is gone is exactly the run most likely to
 * keep going: a loop that is failing makes more calls, not fewer.
 */
function canSpend(state, ceiling) {
    const max = Number(ceiling.maxCostUsd) || 0;
    if (max > 0 && state.costUsd >= max) {
        return {
            ok: false, reason: "budget_limit",
            detail: "this run has spent $" + state.costUsd.toFixed(4) + " of its $" + max.toFixed(2) + " allowance"
        };
    }
    const maxCalls = Number(ceiling.maxCalls) || 0;
    if (maxCalls > 0 && state.calls >= maxCalls) {
        return {
            ok: false, reason: "turn_limit",
            detail: "this run has made " + state.calls + " of its " + maxCalls + " allowed model calls"
        };
    }
    return { ok: true };
}
