/* GENERATED FROM backend/agent-src/
   Do not edit this file. Edit agent-src/codeagent/mongo.ts and run `npm run build:agent`.
   Listed in docs/REPO-MAP.md beside the other generated files. */
"use strict";
/* =================================================================
   mongo.ts — the shape of the database handle, loosely
   -----------------------------------------------------------------
   usage and run-store both take their database by injection —
   `init({ getMasterDb })` — rather than requiring backend/db.js, so
   that the tests can hand them a mock (see test/run-store-test.js,
   which implements just enough of a collection to drive them).

   The types here are deliberately loose. Typing the real driver would
   mean either depending on mongodb's own types across the whole
   subsystem, or writing a fake that the hand-rolled test mocks would
   then fail to satisfy — and the mocks are the point: they implement
   the four methods these modules use and nothing else.

   So this describes what the CALLERS use, not what MongoDB offers. It
   is an honest under-description, and the place a wrong assumption
   shows up is a test, not production.
   ================================================================= */
Object.defineProperty(exports, "__esModule", { value: true });
