/* GENERATED FROM backend/agent-src/
   Do not edit this file. Edit agent-src/types.ts and run `npm run build:agent`.
   Listed in docs/REPO-MAP.md beside the other generated files. */
"use strict";
/* =================================================================
   types.ts — the contracts the agent subsystem agrees on
   -----------------------------------------------------------------
   These are discriminated unions rather than loose objects wherever a
   value has states, because the bugs this subsystem actually had were
   state confusions: a tool result that was sometimes a string and
   sometimes an object, a mode that existed in the schema but not in
   the dispatcher, an approval that was a boolean the client sent.
   ================================================================= */
Object.defineProperty(exports, "__esModule", { value: true });
