/* GENERATED FROM backend/agent-src/
   Do not edit this file. Edit agent-src/lib/codeagent/worker-service.ts and run `npm run build:agent`.
   Listed in docs/REPO-MAP.md beside the other generated files. */
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TERMINAL = void 0;
exports.publicRun = publicRun;
exports.createVerifier = createVerifier;
exports.createFinalizer = createFinalizer;
exports.executeClaim = executeClaim;
const crypto_1 = require("../crypto");
const usage_1 = require("./usage");
/* eslint-disable @typescript-eslint/no-explicit-any */
exports.TERMINAL = new Set(["succeeded", "partial", "failed", "cancelled", "blocked"]);
function publicRun(run) {
    if (!run)
        return null;
    const fields = ["id", "projectId", "chatId", "status", "phase", "createdAt", "updatedAt",
        "latestError", "costUsd", "result", "latestCheckpointId", "cancelled", "cancelReason"];
    return Object.fromEntries(fields.filter(k => run[k] !== undefined).map(k => [k, run[k]]));
}
function createVerifier({ url, token, fetchImpl = globalThis.fetch }) {
    if (!url || !token || token.length < 32)
        throw new Error("Configure AGENT_VERIFIER_URL and a 32+ character AGENT_VERIFIER_TOKEN");
    const endpoint = new URL(url);
    if (!["http:", "https:"].includes(endpoint.protocol) || endpoint.username || endpoint.password)
        throw new Error("Invalid verifier URL");
    /* The deploy plane's convention, not a second one invented here: its
       internal surface authenticates with x-internal-token and compares
       it in constant time (infra/deploy/src/api/auth.js). AGENT_VERIFIER_TOKEN
       and the plane's INTERNAL_TOKEN are the same secret.
  
       Paths are joined RELATIVE to the configured base. `new URL("/health",
       base)` discards the base's path and asks the origin, which would have
       hit the plane's own public /health and read a healthy plane as a
       healthy verifier. */
    async function request(path, body, signal) {
        const base = endpoint.href.endsWith("/") ? endpoint.href : endpoint.href + "/";
        const response = await fetchImpl(new URL(String(path).replace(/^\//, ""), base), {
            method: body ? "POST" : "GET", redirect: "error", signal,
            /* TWO tokens, because there are two gates guarding different
               things. The deploy plane's control hostname is fenced app-wide
               by x-platform-token (auth.js requirePlatformToken) before any
               route is reached; the verifier route is then fenced by
               x-internal-token. Sending only the second gets a 401 from the
               hostname gate and never reaches the route — which is exactly
               what happened the first time this was pointed at production.
      
               DEPLOY_PLATFORM_TOKEN is the variable lib/deployplane.js
               already uses for the same hop, so there is one name for it. */
            headers: Object.assign({ "x-internal-token": token, "Content-Type": "application/json" }, process.env.DEPLOY_PLATFORM_TOKEN ? { "x-platform-token": process.env.DEPLOY_PLATFORM_TOKEN } : {}),
            body: body ? JSON.stringify(body) : undefined
        });
        if (!response.ok)
            throw new Error("Build service returned HTTP " + response.status);
        return response.json();
    }
    return {
        health: () => request("health", null, AbortSignal.timeout(5000)),
        check: (files, context) => request("check", {
            runId: context.runId, checkId: context.checkId, sourceHash: context.sourceHash, files
        }, context.signal)
    };
}
/* The run and the project must agree even if the worker dies just after commit.
   Full source snapshots also survive pruning an earlier revision's delta. */
function createFinalizer({ withTransaction, run, workerId, generation, onAttach }) {
    return async function finalize(outcome, status) {
        if (!exports.TERMINAL.has(status))
            throw new Error("Invalid terminal run state");
        const committed = await withTransaction(async (db, session) => {
            const runs = db.collection("agent_runs");
            const current = await runs.findOne({ id: run.id }, { session });
            if (!current || exports.TERMINAL.has(current.status) || current.cancelled && status !== "cancelled" ||
                current.leaseOwner !== workerId || current.leaseGeneration !== generation ||
                current.leaseExpiresAt <= new Date().toISOString())
                return false;
            const result = Object.assign({}, outcome, { status, projectId: run.projectId });
            const now = new Date().toISOString();
            const project = await db.collection("projects").findOne({ id: run.projectId }, { session });
            if (!project || (run.ownerUserId ? project.ownerUserId !== run.ownerUserId : project.ownerAnonId !== run.ownerAnonId)) {
                throw new Error("Project was deleted or its owner changed while the agent was working");
            }
            result.slug = project.slug;
            if (status === "succeeded" && outcome.files && Object.keys(outcome.files).length && outcome.fileStats && outcome.fileStats.some((f) => f.isNew || f.added || f.removed)) {
                const revisionId = "rv_" + run.id;
                const changed = await db.collection("projects").updateOne({
                    id: project.id, headRevision: run.baseRevisionId || null
                }, { $set: { headRevision: revisionId, updatedAt: now } }, { session });
                if (!changed.matchedCount)
                    throw new Error("Project changed during this run; candidate files are saved, but were not applied");
                await db.collection("revisions").updateOne({ id: revisionId }, { $setOnInsert: {
                        id: revisionId, projectId: project.id, parentId: null,
                        config: { files: outcome.files }, label: String(outcome.summary || "Agent result").slice(0, 60), at: now
                    } }, { upsert: true, session });
                result.revisionId = revisionId;
            }
            const lastTurn = await db.collection("turns").findOne({ projectId: project.id }, { sort: { seq: -1 }, session });
            await db.collection("turns").updateOne({ id: "turn_" + run.id }, { $setOnInsert: {
                    id: "turn_" + run.id, projectId: project.id, seq: ((lastTurn && lastTurn.seq) || 0) + 1,
                    chatId: run.chatId || "", role: "agent", kind: status === "succeeded" ? "result" : "text",
                    body: String(outcome.summary || outcome.reason || status).slice(0, 4000),
                    revisionId: result.revisionId || null, fileStats: outcome.fileStats || [],
                    /* How long it took, so a replayed panel can say "Thought for 47s"
                       the way the live one does. The event stream cannot supply it —
                       the frames carry payloads and not the time each was written — so
                       the turn row is the only place it can come from. */
                    ms: Math.max(0, Date.now() - Date.parse(run.createdAt || "") || 0),
                    // Same reason as ms directly above: a replayed turn should not have
                    // to fetch a whole event stream to say what it cost.
                    tokens: Number(outcome.tokens) || 0,
                    at: now
                } }, { upsert: true, session });
            const usd = Number(outcome.costUsd) || 0;
            if (usd > 0 && !(run.context && run.context.byokEncrypted)) {
                const owner = (0, usage_1.ownerKey)({ userId: run.ownerUserId, anonId: run.ownerAnonId });
                await db.collection("codeagent_usage").updateOne({ owner, month: (0, usage_1.monthKey)() }, {
                    $inc: { costUsd: usd, builds: 1 }, $set: { updatedAt: now }
                }, { upsert: true, session });
                await db.collection("codeagent_usage_events").insertOne({ owner, at: new Date(), usd, runId: run.id }, { session });
            }
            await runs.updateOne({ id: run.id }, { $set: {
                    status, phase: status, result, costUsd: usd, updatedAt: now,
                    /* Persisted, not just returned. The brief asks for explicit stop
                       reasons and the first worker run ended with none on the row:
                       the runner produced one, handed it back, and the only writer
                       of the document never wrote it down. */
                    stopReason: outcome.stopReason || null,
                    latestError: status === "succeeded" ? null : outcome.reason || outcome.summary || status
                }, $unset: {
                    "context.byokEncrypted": "",
                    /* The same three run-store.updateRun releases on a terminal
                       status, and for the same reason: activeOwnerKey carries a
                       unique partial index, so a finished run that keeps it refuses
                       the owner's next build with RUN_ALREADY_ACTIVE for ever.
            
                       It never mattered while nothing called this finalizer —
                       updateRun was doing the release. Making this the one writer
                       moved that duty here, and the first live run after the change
                       came back terminal with all three still set. */
                    activeProjectId: "", activeOwnerKey: "", leaseExpiresAt: ""
                } }, { session });
            return true;
        });
        /* THE PHOTOS BECOME PART OF THE PROJECT HERE, OR THEY EXPIRE.
    
           An upload is litter until something builds with it, so it carries a
           24h TTL that attachToProject clears for ever. Both calls to that
           live in index.js — the in-process path and /build — and neither of
           them runs when the work went to a worker. So on the durable path,
           which is the one production uses, nothing ever claimed the image:
           the row and its bytes kept the expiry and Mongo swept them the next
           day, leaving a published site pointing at a 404. Seen in live data,
           two rows reading "project: NONE, expires tomorrow".
    
           After the commit rather than inside it: the bytes live in a sibling
           database and this transaction is scoped to the master one. A
           successful build whose image could not be marked permanent is worth
           a warning, not a rollback — the revision is already correct. */
        if (committed && status === "succeeded" && typeof onAttach === "function") {
            try {
                await onAttach(run);
            }
            catch (e) {
                console.warn("[worker] could not attach the run's images:", e && e.message);
            }
        }
        return committed;
    };
}
async function executeClaim({ run, workerId, store, runner, verifier, withTransaction, signal, onAttach }) {
    const controller = new AbortController();
    const abort = () => controller.abort(signal && signal.reason);
    if (signal)
        signal.addEventListener("abort", abort, { once: true });
    if (signal && signal.aborted)
        abort();
    const generation = run.leaseGeneration;
    let renewing = false;
    const timer = setInterval(async () => {
        if (renewing)
            return;
        renewing = true;
        try {
            if (!await store.renewLease(run.id, workerId, generation))
                controller.abort(new Error("Worker lease lost"));
        }
        catch (error) {
            controller.abort(error);
        }
        finally {
            renewing = false;
        }
    }, 10000);
    try {
        const context = run.context || {};
        const byok = context.byokEncrypted ? JSON.parse((0, crypto_1.decryptSecret)(context.byokEncrypted)) : undefined;
        return await runner.executeRun(run.id, Object.assign({}, context, {
            byok, signal: controller.signal, claimed: { workerId, generation },
            checkProject: verifier.check,
            finalize: createFinalizer({ withTransaction, run, workerId, generation, onAttach })
        }));
    }
    finally {
        clearInterval(timer);
        if (signal)
            signal.removeEventListener("abort", abort);
    }
}
