/* GENERATED FROM backend/agent-src/
   Do not edit this file. Edit agent-src/worker/codeagent-worker.ts and run `npm run build:agent`.
   Listed in docs/REPO-MAP.md beside the other generated files. */
"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.main = main;
const path = __importStar(require("path"));
// Side-effecting, and it must run before anything reads process.env.
require("dotenv").config({ path: path.join(__dirname, "..", ".env") });
const crypto = __importStar(require("crypto"));
const db = __importStar(require("../db"));
const store = __importStar(require("../lib/codeagent/run-store"));
const runner = __importStar(require("../lib/codeagent/agent-runner"));
const worker_service_1 = require("../lib/codeagent/worker-service");
/* The worker has to make an uploaded photo permanent, same as the route
   does. Both modules are wired exactly as index.js wires them, so the
   two executors clear the expiry through one code path rather than two
   that can drift. */
const uploads = __importStar(require("../lib/uploads"));
const blobs = __importStar(require("../lib/storage/blobs"));
async function main() {
    const verifier = (0, worker_service_1.createVerifier)({ url: process.env.AGENT_VERIFIER_URL, token: process.env.AGENT_VERIFIER_TOKEN });
    await db.connect();
    store.init({ getMasterDb: db.getMasterDb });
    blobs.init({ getMasterDb: db.getMasterDb, getBlobDb: () => db.getSiblingDb("blobs") });
    uploads.init({ getMasterDb: db.getMasterDb, onPersist: (keys) => blobs.persist(keys) });
    await store.ensureIndexes();
    /* The blob store's indexes were created on one path only — the legacy
       in-process SSE build — which this worker replaced, so in production
       neither existed: no unique key to make a retried part overwrite
       itself, and no TTL, so every abandoned upload's bytes stayed forever. */
    await blobs.ensureIndexes();
    const workerId = "agent_" + crypto.randomUUID();
    const shutdown = new AbortController();
    process.once("SIGTERM", () => shutdown.abort());
    process.once("SIGINT", () => shutdown.abort());
    let healthBusy = false;
    async function heartbeat() {
        if (healthBusy)
            return;
        healthBusy = true;
        try {
            const health = await verifier.health();
            await store.workerHeartbeat(workerId, { ready: health.ok === true, version: 1 });
        }
        catch {
            await store.workerHeartbeat(workerId, { ready: false, version: 1 });
        }
        finally {
            healthBusy = false;
        }
    }
    await heartbeat();
    /* Say so. The worker used to start completely silently — it connected
       to Mongo, began claiming, and printed nothing ever again unless a
       run failed. That is indistinguishable from a process that hung, and
       it is what made ship.sh unable to tell a healthy deploy from a dead
       one on the first attempt. */
    const health = await store.getWorkerHealth().catch(() => null);
    console.log("[agent-worker] ready — id " + workerId +
        ", verifier " + ((health && health.healthy) ? "reachable" : "UNREACHABLE") +
        ", claiming from agent_runs");
    const healthTimer = setInterval(() => heartbeat().catch((e) => console.error("[agent-worker] heartbeat:", e.message)), 10000);
    try {
        while (!shutdown.signal.aborted) {
            await store.recoverExpiredRuns();
            const health = await store.getWorkerHealth();
            const run = health.healthy ? await store.claimNext(workerId) : null;
            if (run) {
                try {
                    await (0, worker_service_1.executeClaim)({
                        run, workerId, store, runner, verifier,
                        withTransaction: db.withTransaction, signal: shutdown.signal,
                        /* Called after the finalizer commits. attachToProject clears the
                           24h expiry on the row for ever and fires onPersist, which does
                           the same for the bytes — the one thing standing between a
                           published site and a 404 the day after it was built. */
                        onAttach: async (finished) => {
                            const imgs = (finished.context && finished.context.attachedImages) || [];
                            const ids = imgs.map((i) => i && i.id).filter(Boolean);
                            if (ids.length && finished.projectId)
                                await uploads.attachToProject(ids, finished.projectId);
                        }
                    });
                }
                catch (error) {
                    console.error("[agent-worker] run", run.id, error.message);
                }
            }
            else {
                await new Promise(resolve => { const timer = setTimeout(resolve, 1000); if (shutdown.signal.aborted) {
                    clearTimeout(timer);
                    resolve();
                } });
            }
        }
    }
    finally {
        clearInterval(healthTimer);
        await store.workerHeartbeat(workerId, { ready: false, version: 1 });
        await db.close();
    }
}
if (require.main === module)
    main().catch((error) => { console.error("[agent-worker]", error.message); process.exitCode = 1; });
